config/routes.rb
Rails.application.routes.draw do
 
 root 'static_pages#home'
  
 get 'orderitems/index'
 get 'orderitems/show'
 get 'orderitems/new'
 get 'orderitems/edit'
 
 get '/checkout' => 'cart#createOrder'

 resources :orders do
  resources:orderitems
 end
 
 resources :items
 
 get 'cart/index'

 get '/home' => 'static_pages#home'
 get '/about' => 'static_pages#about'
 get '/help' => 'static_pages#help'
 
 get '/register' => 'registrations#new'
 get '/login' => 'sessions#new'
 
 
 get '/cart/clear', to: 'cart#clear'
 get '/cart', to: 'cart#index'
 get '/cart/:id', to: 'cart#add'
 get '/cart/remove/:id', to: 'cart#remove'
 get '/cart/decrease/:id', to: 'cart#decrease'
 get '/cart/increase/:id', to: 'cart#increase'
 
 
 get '/payments' => 'orders#pay'
 get '/shipped/:id' => 'orders#shipped'
 
 post '/search' => 'items#search'
 
 resources :categories
 get '/category/:title', to: 'static_pages#category'
 


  resources :posts
  
  #devise_for :users, controllers: {registrations: "registrations"}
  devise_for :users do 
   resources :orders 
  end
  
 get '/paid/:id' => 'static_pages#paid'
 get '/aboutSend/:id' => 'static_pages#aboutSend'
 
  
 get 'admin/admin'

 get '/createuser' => 'sign_in#createuser'
  
 get '/signIn' => 'sign_in#signin'
  
 get '/adminsignin' => 'sign_in#adminsignin'

  #get 'sign_in/AdminSignIn'
  
  #get 'sign_in/SignIn'
  
  #get 'sign_in/CreateUser'

  root 'home#index'
  
 

  resources :home
  devise_for controllers: {registrations: "registrations"}
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def search
  st = "%#{params[:q]}%"
  @items = Item.where("title like ?", st)
  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :author, :genre, :description, :price, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">
<h1>Items</h1>
<% @items.each do |item| %>

<div class="itemhols">
    <h1><%= item.title %></h1>
        <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
    <p><%= item.description %></p>
    <p>Price <%= number_to_currency(item.price, :unit => "€") %>
    <br>
        Author: <%= item.author %>
    <br>
        Genre: <%= item.genre %></p>
    <br>
        Category: <%#= item.category %>
    <p>
        <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
            <%= link_to 'Show', item, :class => "button", :role => "button" %>
            <%= link_to 'Edit', edit_item_path(item), :class => "button", :role => "button" %>
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
    </p>
</div>
<% end %>
</div>

</table>

<br>

<%= link_to 'New Item', new_item_path, :class =>"button", :role=>"button"%>

<%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button" %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>
<% if @items.length == 0 %>
<br />
<h2>No products were found to match your search</h2>
<% end %>
<table class="catalog">
<% @items.each do |item| %>
<tr>
<td>
<div class="image">
<%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
</div>
<div class="title">
<%= link_to item.title, item %>
</div>
<div class="description">
<%= item.description %>
</div>
<div class="price">
<%= number_to_currency(item.price, :unit => "€") %>
</div>
<div class="links">
<% if user_signed_in? %>
<%= link_to 'Edit', edit_item_path(item) %>
<%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
<%else%>
<a href="/cart/<%= item.id %>">Add to Cart</a>
<%end%>
</div>
</td>
</tr>
<% end %>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">
<h1><%= @item.title %></h1>
<%= image_tag @item.image_url, :class => 'welcomIm' %>
<h2><%= @item.description %></h1>
<div class="itemhols">
<p>Price <%= number_to_currency(@item.price, :unit => "€") %>
<br>
Author: <%= @item.author %>
<br>
Genre: <%= @item.genre %></p>
<br>
Category: <%#= @item.category %>
<p>
<%= link_to 'Back', items_path, :class => "button", :role => "button" %>
<%= link_to 'Edit', edit_item_path(@item), :class => "button", :role => "button" %>
</p>
</div>
</div>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>